[package]
name = "howler"
version = "0.1.0"
authors = ["Shekhinah Memmel <she@khinah.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
